{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:39:13Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5613",
  "aliases": [
    "SNYK-PYTHON-PYCORG-6513669"
  ],
  "summary": "Malicious code in py-corg (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py-corg",
        "purl": "pkg:pypi/py-corg"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCORG-6513669"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "29790ea3e2923de1bc48e73908c2c0484f453ae483334904be59e2affc8015f0",
        "import_time": "2024-06-28T02:49:55.255949509Z",
        "id": "RLMA-2024-04395",
        "modified_time": "2024-06-25T13:39:13Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "dea0e5b7d9534e90af780f9972ab880e0ba5f05fd6c41af820b300671748f1c1",
        "import_time": "2024-10-24T00:59:44.624727499Z",
        "id": "RLUA-2024-08828",
        "modified_time": "2024-10-16T14:46:52Z"
      }
    ]
  }
}
