{
  "modified": "2024-10-24T01:01:58Z",
  "published": "2024-06-25T13:36:50Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5313",
  "aliases": [
    "SNYK-PYTHON-LIBIDEE-5885051"
  ],
  "summary": "Malicious code in libidee (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "libidee",
        "purl": "pkg:pypi/libidee"
      },
      "versions": [
        "0.1"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-LIBIDEE-5885051"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "1e39613723af8e2c9ea67441033c54bdba64df420bd11534cd8dda9c7d79d353",
        "import_time": "2024-06-28T02:49:20.134799114Z",
        "id": "RLMA-2024-04095",
        "modified_time": "2024-06-25T13:36:50Z",
        "versions": [
          "0.1"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "8c0a8ef6f8e2db53a17a4dab7bfdcc88bf825e84efb67cec43cff2abae4566b0",
        "import_time": "2024-10-24T00:59:23.785867711Z",
        "id": "RLUA-2024-08459",
        "modified_time": "2024-10-16T14:43:07Z"
      }
    ]
  }
}
