{
  "modified": "2024-10-24T01:01:58Z",
  "published": "2024-06-25T13:32:48Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-4816",
  "aliases": [
    "SNYK-PYTHON-BIPUTTILS-6513722"
  ],
  "summary": "Malicious code in bip-uttils (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "bip-uttils",
        "purl": "pkg:pypi/bip-uttils"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-BIPUTTILS-6513722"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "b84a7820945f536c756d68f157cba4f9a85b459ea80ca4325541edd18dd4f40d",
        "import_time": "2024-06-28T02:48:21.695044491Z",
        "id": "RLMA-2024-03596",
        "modified_time": "2024-06-25T13:32:48Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "694f32c1ad1e70477ea0a73de960101e7af6bb88ce5331db1bbec41c923d82db",
        "import_time": "2024-10-24T00:58:49.916278523Z",
        "id": "RLUA-2024-07875",
        "modified_time": "2024-10-16T14:36:57Z"
      }
    ]
  }
}
