{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:39:14Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5614",
  "aliases": [
    "SNYK-PYTHON-PYCORID-6513247"
  ],
  "summary": "Malicious code in py-corid (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py-corid",
        "purl": "pkg:pypi/py-corid"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCORID-6513247"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "605bb75fc35c7d97f2cc4b4312e45af2f7c87146459f6c60c8ea8c3b6fc12121",
        "import_time": "2024-06-28T02:49:55.380455327Z",
        "id": "RLMA-2024-04396",
        "modified_time": "2024-06-25T13:39:14Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "9290cdaa32fe8c1fb313b8d056908707a34a2ca030e99b428ddef11610bef451",
        "import_time": "2024-10-24T00:59:44.674279061Z",
        "id": "RLUA-2024-08829",
        "modified_time": "2024-10-16T14:46:53Z"
      }
    ]
  }
}
