{
  "modified": "2024-10-24T01:01:59Z",
  "published": "2024-06-25T13:38:59Z",
  "schema_version": "1.5.0",
  "id": "MAL-2024-5583",
  "aliases": [
    "SNYK-PYTHON-PYCDORD-6513306"
  ],
  "summary": "Malicious code in py-cdord (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py-cdord",
        "purl": "pkg:pypi/py-cdord"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCDORD-6513306"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "a005a3be604c9efac1d53bfbc47f89cd38dd4d82d23c500336eca05b841d5a50",
        "import_time": "2024-06-28T02:49:51.683850751Z",
        "id": "RLMA-2024-04365",
        "modified_time": "2024-06-25T13:38:59Z",
        "versions": [
          "1.0.0"
        ]
      },
      {
        "source": "reversing-labs",
        "sha256": "ff5a88e62a8fe5d8cde0cabda1cba2df21475553e37fac6f58031a64b9cd2406",
        "import_time": "2024-10-24T00:59:42.310643171Z",
        "id": "RLUA-2024-08798",
        "modified_time": "2024-10-16T14:46:34Z"
      }
    ]
  }
}
