{
  "modified": "2025-08-28T07:11:11Z",
  "published": "2025-08-28T07:11:11Z",
  "schema_version": "1.5.0",
  "id": "MAL-2025-41687",
  "summary": "Malicious code in iamenumer (PyPI)",
  "details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "iamenumer",
        "purl": "pkg:pypi/iamenumer"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "id": "RLMA-2025-04179",
        "import_time": "2025-08-29T06:41:45.597481469Z",
        "modified_time": "2025-08-28T07:11:11Z",
        "sha256": "2fb779637806a688c42fc467de4ed9d7aa7deb1817c44a9ca99d6023fa3a4a28",
        "source": "reversing-labs",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
