{
  "modified": "2025-08-06T01:01:03Z",
  "published": "2025-08-06T01:01:03Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "PYSEC-2025-72",
    "GHSA-jxr6-qrxx-2ph2"
  ],
  "summary": "Malicious code in num2words (pypi)",
  "details": "The num2words project was compromised via a phishing attack and two new\nversions were uploaded to PyPI containing malicious code.\n",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "num2words"
      },
      "versions": [
        "0.5.15",
        "0.5.16"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://nitter.tiekoetter.com/SFLinux/status/1949906299308953827"
    },
    {
      "type": "ARTICLE",
      "url": "https://www.stepsecurity.io/blog/supply-chain-security-alert-num2words-pypi-package-shows-signs-of-compromise"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "google-open-source-security",
        "sha256": "36822c42f7e862f29cef9734efec9a9a9cc44a80e619e954dd25c12239d15767",
        "import_time": "2025-08-06T01:07:01.055679Z",
        "modified_time": "2025-08-06T01:01:03Z",
        "versions": [
          "0.5.15",
          "0.5.16"
        ]
      }
    ]
  }
}
